name: CHATS
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+50 #Always change build number to a new number before building for release

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  email_auth: ^0.0.1+2
  http_parser: ^4.0.0
  dio: ^4.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  flutter_datetime_picker: ^1.5.1
  font_awesome_flutter: ^9.1.0
  dotted_border: ^2.0.0
  provider: ^5.0.0
  # pin_entry_text_field: ^0.1.4
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  date_format: ^2.0.2
  # local_auth: ^1.1.6
  carousel_slider: ^4.0.0
  get_it: ^7.1.3
  image_picker: ^0.8.0+4
  path_provider: ^2.0.2
  flutter_spinkit: ^5.0.0
  flutter_barcode_scanner: ^2.0.0
  fl_chart: ^0.36.2

  path:

  google_fonts: ^2.1.0
  analyzer: ^1.7.1
  barcode_scan2: ^4.1.3
  snack: ^2.0.0
  flutter_local_auth_invisible: ^2.2.0
  location: ^4.4.0
  # geolocator: ^6.2.1
  geocoder: ^0.2.1
  # nfc_manager: ^3.1.1
  bottom_drawer: ^0.0.5
  jiffy: ^5.0.0
  url_launcher: ^6.1.4
  liquid_pull_to_refresh: ^3.0.1
  flutter_markdown: ^0.6.10+3
  unique_identifier: ^0.2.2
  device_info_plus: ^4.1.2
  flutter_password_strength: ^0.1.6
  rxdart: ^0.27.5
  permission_handler: ^10.2.0
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

scripts:
  build_bundle: flutter build appbundle --release --no-sound-null-safety -v

flutter_icons:
  image_path: "assets/icons/chats_bene_app_icon_3.png"
  android: "launcher_icon"
  ios: true

flutter:
  assets:
    - assets/
    - icons/
    - assets/images/
    - assets/icons/
    # - assets/icons/chats_bene_app_icon_2.png
    - assets/icons/chats_bene_app_icon_3.png
    - assets/images/chats_login_transparent.png
    - assets/images/chats_login_transparent_green.png
    - assets/CountryCodes.json

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy-bold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.ttf
        # - asset: fonts/Gilroy-Light.ttf
    #         style: italic
    - family: Gilroy-medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
        # - asset: fonts/Gilroy-Light.ttf
    #         style: italic
    - family: Gilroy-Regular
      fonts:
        - asset: fonts/Gilroy-Light.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
