export 'package:CHATS/screens/Home/Views/account.dart';
export 'package:CHATS/screens/Home/Views/all_campaigns_view.dart';
export 'package:CHATS/screens/Home/Views/bvn_verification_form.dart';
export 'package:CHATS/screens/Home/Views/campaigns_view.dart';
export 'package:CHATS/screens/Home/Views/change_password_view.dart';
export 'package:CHATS/screens/Home/Views/change_pin_view.dart';
export 'package:CHATS/screens/Home/Views/complaint_view.dart';
export 'package:CHATS/screens/Home/Views/help_support_view.dart';
export 'package:CHATS/screens/Home/Views/home_view.dart';
export 'package:CHATS/screens/Home/Views/kyc_status.dart';
export 'package:CHATS/screens/Home/Views/notifications_view.dart';
export 'package:CHATS/screens/Home/Views/onboard_screen.dart';
export 'package:CHATS/screens/Home/Views/payment_confirmation_view.dart';
export 'package:CHATS/screens/Home/Views/personal_info_view.dart';
export 'package:CHATS/screens/Home/Views/profile_view.dart';
export 'package:CHATS/screens/Home/Views/reset_password_view.dart';
export 'package:CHATS/screens/Home/Views/scan_NFC_or_OR_view.dart';
export 'package:CHATS/screens/Home/Views/security_view.dart';
export 'package:CHATS/screens/Home/Views/set_pin_view.dart';
export 'package:CHATS/screens/Home/Views/settings_view.dart';
export 'package:CHATS/screens/Home/Views/splashscreen.dart';
// export 'package:CHATS/screens/Home/Views/profile/account_settings_view.dart';
// export 'package:CHATS/screens/Home/Views/profile/card_and_payment_view.dart';
// export 'package:CHATS/screens/Home/Views/profile/profile_settings_view.dart';
// export 'package:CHATS/screens/Home/Views/profile/profile_view.dart';
// export 'package:CHATS/screens/Home/Views/profile/security_view.dart';
// export 'package:CHATS/screens/Home/Views/profile/support_view.dart';
export 'package:CHATS/screens/Home/Views/tasks_view.dart';
export 'package:CHATS/screens/Home/Views/transaction_pin_view.dart';
export 'package:CHATS/screens/Home/Views/wallet_view.dart';
